# -*- coding: utf-8 -*-
"""flood_modelling_HANDS_method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GS4cTHOwNnIva9WAKe4qrEi86X92k3-F

# Height Above Nearest Drainage (HAND) Modeling in Python

## Overview
The **Height Above Nearest Drainage (HAND)** model is a terrain model derived from a Digital Elevation Model (DEM). Unlike standard DEMs that measure absolute elevation above sea level, HAND measures **relative vertical distance** from any point on a landscape to the nearest stream or drainage point along its natural gravitational flow path.

### Key Applications
1. **Rapid Flood Inundation Mapping:** Fast estimation of flooded areas for given stage rises ($\text{Inundation Mask} = \text{HAND} \le \text{Stage Height}$).
2. **Soil Saturated Zone Zonation:** Identifying water table proximity and wetland hydrology.
3. **Low-Cost Hydro-Geomorphology:** Scalable processing over large catchments without complex hydrodynamic differential equations.

### Mathematical Formulation
For any given terrain cell $c$:
$$\text{HAND}(c) = Z(c) - Z(\text{Stream}_{\text{target}})$$

Where $Z(c)$ is the elevation of the cell, and $Z(\text{Stream}_{\text{target}})$ is the elevation of the stream cell reached by following the steepest downhill flow path from $c$.
"""

# Commented out IPython magic to ensure Python compatibility.
# #@title Step 1A. Run Initial Setup - Installations
# #@markdown **Important:** Run this cell to install dependencies.
# 
# %%capture
# !pip install -q geemap ipyleaflet pillow matplotlib
# !pip -q install earthengine-api pysheds rasterio matplotlib hydrafloods localtileserver rasterio rio-cogeo shapely
# !pip -q install tqdm fiona

# Commented out IPython magic to ensure Python compatibility.
# #@title Step 1B. Run Initial Setup
# #@markdown **Important:** Run this cell to import and initialize the system environment.
# 
# %%capture
# import ee
# import glob, rasterio
# from shapely.geometry import box, mapping
# from google.colab import drive

#@title Step 1C. Separately Import GEEMAP
#@markdown **Important:** Run this cell to import geemap that was conflicting with newer Colab Dependencies

import geemap

#@title Step 2: Setup Google Earth Engine (GEE)
#@markdown **Important:** You must specify your Google Cloud Project name below to authenticate with Earth Engine.
#@markdown
#@markdown If you do not have a GEE account or project:
#@markdown 1. Sign up at [code.earthengine.google.com](https://code.earthengine.google.com/).
#@markdown 2. Go to the [Google Cloud Console](https://console.cloud.google.com/).
#@markdown 3. Create a new project or select an existing one.
#@markdown 4. Enable the 'Earth Engine API' for your project.
#@markdown 5. Copy the **Project ID** and paste it into the `PROJECT_NAME` field below.

#connect gdrive socket
drive.mount('/content/drive')

PROJECT_NAME = 'sarai-clseams-playground' #@param {type:"string"}

import ee
try:
    ee.Authenticate()
    ee.Initialize(project=PROJECT_NAME)
    print(f"Successfully initialized Earth Engine with project: {PROJECT_NAME}")
except Exception as e:
    print(f"Initialization failed: {e}")

#@title Load Important Helper Functions
#@markdown **Important:** Run this!!!

import os
import numpy as np
import rasterio
import matplotlib.pyplot as plt
from pysheds.grid import Grid
import base64
import io
from PIL import Image
from ipyleaflet import Map, ImageOverlay, LayersControl, basemaps
from google.colab import output
import ee, json
from rasterio.mask import mask
from rasterio.warp import transform_geom

output.enable_custom_widget_manager()

from PIL import Image
from ipyleaflet import (
    Map,
    ImageOverlay,
    LayersControl,
    basemaps,
    basemap_to_tiles
)

def depth_tif_to_data_url(depth_path, stage_m, cmap_name="turbo"):
    """
    Converts a flood-depth GeoTIFF into an RGBA PNG data URL.

    Pixels with no flooding or nodata become fully transparent.
    Flooded pixels are colored according to depth.
    """
    with rasterio.open(depth_path) as src:
        depth = src.read(1).astype("float32")
        nodata = src.nodata
        bounds = src.bounds

    valid = np.isfinite(depth)

    if nodata is not None:
        valid &= depth != nodata

    # Only positive inundation depth should be visible
    valid &= depth > 0

    # Normalize depth to 0–1 using the corresponding stage
    normalized = np.zeros_like(depth, dtype=np.float32)
    normalized[valid] = np.clip(depth[valid] / float(stage_m), 0, 1)

    cmap = plt.get_cmap(cmap_name)
    rgba = (cmap(normalized) * 255).astype(np.uint8)

    rgba[..., 3] = np.where(valid, 220, 0).astype(np.uint8)

    # Raster row zero is north/top, which is correct for ImageOverlay
    image = Image.fromarray(rgba, mode="RGBA")

    buffer = io.BytesIO()
    image.save(buffer, format="PNG")

    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")
    data_url = f"data:image/png;base64,{encoded}"

    leaflet_bounds = [
        [bounds.bottom, bounds.left],
        [bounds.top, bounds.right]
    ]

    return data_url, leaflet_bounds

def root_folder():
  root = os.getcwd()
  if not os.path.exists(os.path.join(root, 'dem_temporary')):
    os.makedirs(os.path.join(root, 'dem_temporary'))
  return os.path.join(root, 'dem_temporary')

def pick_stream_threshold(acc, frac=0.3):
    """Choose a threshold so that approximately `frac` of pixels are streams."""
    a = acc.astype("float32")
    a[~np.isfinite(a)] = np.nan
    q = 100 * (1 - frac)
    thr = np.nanpercentile(a, q)
    return thr

def get_aoi_from_map(m):
    aoi = None
    if hasattr(m, "user_roi") and m.user_roi is not None:
        aoi = m.user_roi
    if aoi is None and hasattr(m, "draw_features") and m.draw_features:
        feat = m.draw_features[-1]
        if isinstance(feat, ee.geometry.Geometry):
            aoi = feat
        elif isinstance(feat, ee.feature.Feature):
            aoi = feat.geometry()
        elif isinstance(feat, dict) and "geometry" in feat:
            aoi = ee.Geometry(feat["geometry"])
    if aoi is None:
        aoi = ee.Geometry.Rectangle([121.22, 14.12, 121.28, 14.18])
        print("No AOI drawn. Using fallback rectangle near Bay, Laguna.")
    return aoi

def compute_hand_from_dem(dem_path, streams_acc_threshold=2000, out_hand="/content/hand.tif"):
    grid = Grid.from_raster(dem_path)
    dem  = grid.read_raster(dem_path)
    dem = grid.fill_pits(dem)
    dem = grid.fill_depressions(dem)
    dem = grid.resolve_flats(dem)
    fdir = grid.flowdir(dem)
    acc  = grid.accumulation(fdir)
    streams = acc > streams_acc_threshold
    hand = grid.compute_hand(fdir, dem, streams)
    grid.to_raster(hand, out_hand)
    return out_hand

def depth_tif_to_data_url(depth_path, stage_m, cmap_name="turbo"):
    with rasterio.open(depth_path) as src:
        depth = src.read(1).astype("float32")
        nodata = src.nodata
        bounds = src.bounds
    valid = np.isfinite(depth)
    if nodata is not None: valid &= depth != nodata
    valid &= depth > 0
    normalized = np.zeros_like(depth, dtype=np.float32)
    normalized[valid] = np.clip(depth[valid] / float(stage_m), 0, 1)
    cmap = plt.get_cmap(cmap_name)
    rgba = (cmap(normalized) * 255).astype(np.uint8)
    rgba[..., 3] = np.where(valid, 220, 0).astype(np.uint8)
    image = Image.fromarray(rgba, mode="RGBA")
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")
    data_url = f"data:image/png;base64,{encoded}"
    overlay_bounds = [[bounds.bottom, bounds.left], [bounds.top, bounds.right]]
    return data_url, overlay_bounds

def eegeom_to_geojson_geom(aoi):
    """Convert ee.Geometry to a GeoJSON geometry dict."""
    return aoi.getInfo()  # already a GeoJSON-like geometry dict

def clip_dem_to_aoi(dem_path, aoi_ee, out_path="/content/dem_aoi.tif"):
    """Clips a local DEM (GeoTIFF) to an Earth Engine Geometry (AOI)."""
    aoi_geom = eegeom_to_geojson_geom(aoi_ee)

    with rasterio.open(dem_path) as src:
        src_crs = src.crs

        # AOI from geemap is usually EPSG:4326; transform if DEM CRS differs
        geom_for_mask = aoi_geom
        # Check if the AOI CRS is different from the DEM CRS and transform if needed
        if src_crs and str(src_crs).lower() not in ["epsg:4326", "wgs84"] and aoi_geom['type'] != 'Point': # Points don't need transformation for masking
            # Fiona expects a list of geometries for masking
            geom_for_mask = transform_geom("EPSG:4326", src_crs, aoi_geom)

        out_img, out_transform = mask(src, [geom_for_mask], crop=True)
        out_meta = src.meta.copy()

    out_meta.update({
        "height": out_img.shape[1],
        "width": out_img.shape[2],
        "transform": out_transform,
        "compress": "LZW"
    })

    with rasterio.open(out_path, "w", **out_meta) as dst:
        dst.write(out_img)

    return out_path

#@title NOTE: Just Run this to Initialize Maps
#@markdown ##Drawing AOI manually is not supported
#@markdown ___
#@markdown For some reason, `iPyWidgets` [a dependency of google colab], was not working properly in later
#@markdown colab versions. Just run this, trust me.


m = geemap.Map(basemap="HYBRID", center=[15.45950727088082, 120.97557270401866], zoom=13)
m.add_basemap("SATELLITE")


m.draw_features
m

#@title Step 3: Define Area of Interest (AOI) from Map or Uploaded File (KML/ZIP)
#@markdown Upload a `.kml` or a `.zip` containing shapefile components (`.shp`, `.shx`, `.dbf`, etc.).

import os
import zipfile
import tempfile
import fiona
import ee
from shapely.geometry import shape
from google.colab import files

USE_KML_SHP_AOI = True #@param {type:"boolean"}

def extract_shp_from_zip(zip_path, extract_dir):
    """
    Extracts a zip file and locates the main .shp file path.
    """
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)

    # Search for the .shp file inside the extracted files
    for root, _, files_list in os.walk(extract_dir):
        for file in files_list:
            if file.lower().endswith('.shp'):
                return os.path.join(root, file)
    return None

def get_aoi_from_file(uploaded_file_path):
    """
    Dynamically determines file type (.kml or .zip shapefile),
    parses geometry using fiona, and converts it to an ee.Geometry.
    """
    target_path = uploaded_file_path

    # Handle Zipped Shapefiles dynamically
    if uploaded_file_path.lower().endswith('.zip'):
        temp_dir = tempfile.mkdtemp()
        shp_path = extract_shp_from_zip(uploaded_file_path, temp_dir)
        if not shp_path:
            print("Error: No valid .shp file found inside the uploaded ZIP archive.")
            return None
        target_path = shp_path

    try:
        # Fiona automatically handles KML driver and SHP driver based on file extension
        with fiona.open(target_path, 'r') as source:
            if len(source) == 0:
                print(f"Warning: No features found in {target_path}")
                return None

            # Combine all features into a single geometry if multiple exist
            geoms = [shape(feature['geometry']) for feature in source if feature.get('geometry')]
            if not geoms:
                print("Warning: No valid geometries found.")
                return None

            # If there's only one feature, use it; otherwise, unary_union merges multi-polygons/features
            if len(geoms) == 1:
                combined_geom = geoms[0]
            else:
                from shapely.ops import unary_union
                combined_geom = unary_union(geoms)

            # Convert to ee.Geometry
            if combined_geom.geom_type == 'Point':
                return ee.Geometry.Point(list(combined_geom.coords)[0])
            else:
                return ee.Geometry(combined_geom.__geo_interface__)

    except Exception as e:
        print(f"Error processing file {uploaded_file_path}: {e}")
        return None

aoi_from_file = None
if USE_KML_SHP_AOI:
    print("Please upload your KML or ZIP file (containing .shp, .shx, .dbf):")
    try:
        uploaded = files.upload()
        if uploaded:
            fname = list(uploaded.keys())[0]
            print(f"Uploaded file: {fname}")
            aoi_from_file = get_aoi_from_file(fname)
            if aoi_from_file:
                print("Successfully created AOI from uploaded file.")
            else:
                print("Failed to create AOI from file. Falling back to map drawing.")
        else:
            print("No file uploaded. Falling back to map drawing.")
    except Exception as e:
        print(f"Error during file upload: {e}")

# Set final AOI
if USE_KML_SHP_AOI and aoi_from_file is not None:
    aoi = aoi_from_file
    print("AOI set from uploaded file.")
else:
    aoi = get_aoi_from_map(m)
    print("AOI set from map drawing or fallback.")

#@title Step 4: Acquire DEM (GEE or Local Upload)
#@markdown You can either use the satellite data from Google Earth Engine OR upload your own `.tif` DEM file below.

import os
import rasterio
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files

# --- 1. OPTIONAL: Local File Upload ---
#@markdown **Check the box below if you want to upload a local file:**
USE_UPLOADED_FILE = True #@param {type:"boolean"}

dem_path = os.path.join(root_folder(), 'dem_file.tif') if 'root_folder' in globals() else '/content/dem_file.tif'

if USE_UPLOADED_FILE:
    print("Please click 'Browse' below to upload your DEM .tif file:")
    try:
        uploaded = files.upload()
        if uploaded and len(uploaded) > 0:
            # Get the first filename uploaded
            fname = list(uploaded.keys())[0]
            # Move/Rename to our standard path
            if os.path.exists(dem_path):
                os.remove(dem_path)  # Clean up existing files to avoid conflicts
            os.rename(fname, dem_path)
            print(f"\nSuccessfully using uploaded file: {fname}")

            # Clip the uploaded DEM using the AOI from Step 3
            if 'aoi' in globals() and aoi is not None:
                print("Clipping uploaded DEM with defined AOI...")
                clipped_dem_path = os.path.join(root_folder(), 'clipped_uploaded_dem.tif')
                # Ensure the original dem_path is passed, and the output path is new
                dem_path = clip_dem_to_aoi(dem_path, aoi, out_path=clipped_dem_path)
                print(f"Uploaded DEM clipped and saved to: {dem_path}")
            else:
                print("Warning: No valid AOI found from Step 3 for clipping uploaded DEM. Using full uploaded DEM.")

        else:
            print("\nUpload canceled or no file chosen.")
    except Exception as e:
        print(f"\nAn error occurred during file upload widget initialization: {e}")
else:
    # --- 2. GEE Extraction ---
    # aoi is already defined from Step 3
    if 'aoi' in globals() and aoi is not None:
        scale = 30
        print("Extracting DEM from GEE...")
        dem_ee = ee.ImageCollection("JAXA/ALOS/AW3D30/V4_1").select('DSM').mosaic().clip(aoi)
        try:
            geemap.ee_export_image(dem_ee, filename=dem_path, scale=scale, region=aoi, file_per_band=False)
            print("GEE DEM saved:", dem_path)
        except Exception as e:
            print(f"An error occurred during GEE export: {e}")
    else:
        print("Error: No valid AOI found. Cannot extract DEM from GEE.")
        dem_path = None # Ensure dem_path is None to prevent further processing

# --- 3. Load and Visualize ---
if os.path.exists(dem_path):
    with rasterio.open(dem_path) as src:
        dem = src.read(1).astype("float32")
        nod = src.nodata
        prof = src.profile

    # Handle NaN values for display
    dem_display = dem.copy()
    if nod is not None:
        dem_display[dem_display == nod] = np.nan
    # Extra check for common arbitrary no-data bounds (e.g., -9999)
    dem_display[dem_display < -9000] = np.nan

    print("\n--- DEM Metadata ---")
    print("DEM shape:", dem_display.shape)
    print(f"DEM min/max (m): {np.nanmin(dem_display):.2f}m / {np.nanmax(dem_display):.2f}m")

    plt.figure(figsize=(10, 5))
    plt.imshow(dem_display, interpolation="nearest", cmap='terrain')
    plt.title("Current Project DEM")
    plt.colorbar(label="Elevation (m)")
    plt.axis("off")
    plt.show()
else:
    print("Error: No DEM file found at", dem_path)

#@title Step 5: Drain Treshold
#@markdown Set the drain and mask treshold (0.01 - 0.0001) enough to see drain channels.

# --- PARAMS ---
STREAM_TRESH = .017 #@param {type:"number"}
# --------------

grid = Grid.from_raster(dem_path)
dem = grid.read_raster(dem_path).astype("float32")

# Condition DEM
dem = grid.fill_pits(dem)
dem = grid.fill_depressions(dem)
dem = grid.resolve_flats(dem)

fdir = grid.flowdir(dem)
acc  = grid.accumulation(fdir)

thr = pick_stream_threshold(acc, frac=STREAM_TRESH)  # start here; adjust if needed
streams = acc >= thr

print("Chosen acc threshold:", thr)
print("Stream pixel %:", streams.mean() * 100)

hand = grid.compute_hand(fdir, dem, streams)

hand_path = os.path.join(root_folder(), 'hand_file.tif')
grid.to_raster(hand, hand_path)
print("HAND saved:", hand_path)


with rasterio.open(hand_path) as src:
    hand_arr = src.read(1).astype("float32")
    nod = src.nodata

if nod is not None:
    hand_arr[hand_arr == nod] = np.nan

print("HAND min/max (m):", np.nanmin(hand_arr), np.nanmax(hand_arr))
print("HAND nan %:", np.isnan(hand_arr).mean() * 100)

plt.figure(figsize=(8,5))
plt.imshow(hand_arr, interpolation="nearest", cmap='hot')
plt.title("HAND (m)")
plt.colorbar(label="m above drainage")
plt.axis("off")
plt.show()

#@title Step 6: Run Interactive Inundation Viewer
#@markdown If you are good with the initial treshold, run this cell and run the slider to simulate.

#@markdown Dont forget to set the maximum number of stage in max_ent variable. `max_ent` correspond to maximum entries
#@markdown in which the system will calculate. The values is in meters.

import ipywidgets as widgets
from IPython.display import display

cmaps = 'turbo'
max_ent = 3 #@param {type:'integer'}
def inundation_from_stage(hand, stage_m):
    inund = np.where(np.isfinite(hand) & (hand <= stage_m), 1, 0).astype(np.uint8)
    depth = np.where(np.isfinite(hand), np.maximum(stage_m - hand, 0), np.nan).astype(np.float32)
    return inund, depth

def plot_inundation(stage_m):
    inund, depth = inundation_from_stage(hand_arr, stage_m)

    plt.figure(figsize=(18,6))

    plt.subplot(1,3,1)
    plt.imshow(hand_arr, interpolation="nearest", cmap=cmaps)
    plt.title("HAND (m)")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(inund, interpolation="nearest", cmap=cmaps)
    plt.title(f"Extent (stage={stage_m:.2f} m)")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(depth, interpolation="nearest", cmap=cmaps)
    plt.title(f"Depth (m): max(stage - HAND, 0)")
    plt.colorbar(label="m above drainage")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

slider = widgets.FloatSlider(value=1.0, min=0.0, max=max_ent, step=0.1, description="Stage (m)")
ui = widgets.interactive(plot_inundation, stage_m=slider)
display(ui)

#@title Step 7: Run to generate and save files
import os
import glob
import numpy as np
import rasterio

# Set the number of interval frames when animating.
interval: int = 14 #@param {type:"integer"}

# Clean up existing output files before generating new ones
for pattern in ["/content/hand_extent_stage_*.tif", "/content/hand_depth_stage_*.tif"]:
    for old_file in glob.glob(pattern):
        try:
            os.remove(old_file)
            print(f"Removed previous file: {os.path.basename(old_file)}")
        except OSError as e:
            print(f"Error removing {old_file}: {e}")

# Generate evenly spaced stages as FLOATS from 0.5m (or 1.0m) up to max_ent
stage_levels = np.linspace(0.1, max_ent, interval, dtype='float64').tolist()
stage_levels = [round(s, 2) for s in stage_levels]  # Round neatly to 2 decimal places

print(f"\nGenerated {len(stage_levels)} stage levels:", stage_levels)

def write_geotiff(path, arr, profile, dtype, nodata_val=0):
    prof = profile.copy()
    prof.update(dtype=dtype, count=1, nodata=nodata_val, compress="LZW")
    with rasterio.open(path, "w", **prof) as dst:
        dst.write(arr.astype(dtype), 1)

out_files = []  # keep paths for mapping

with rasterio.open(hand_path) as src:
    base_profile = src.profile

for s in stage_levels:
    inund = np.where(np.isfinite(hand_arr) & (hand_arr <= s), 1, 0).astype(np.uint8)
    depth = np.where(inund == 1, np.maximum(s - hand_arr, 0), 0).astype(np.float32)

    ext_path  = f"/content/hand_extent_stage_{s:.2f}m.tif"
    dep_path  = f"/content/hand_depth_stage_{s:.2f}m.tif"

    write_geotiff(ext_path, inund, base_profile, rasterio.uint8, nodata_val=0)
    write_geotiff(dep_path, depth, base_profile, rasterio.float32, nodata_val=0)

    out_files.append((s, ext_path, dep_path))

print(f"\nSuccessfully saved {len(out_files)} unique raster stages to out_files.")

#@title Step 8: Run to Generate Animation for Progression
import os
import numpy as np
import rasterio
import matplotlib.pyplot as plt
import imageio
from IPython.display import Image as DisplayImage
from tqdm.notebook import tqdm

# --- Configuration ---
use_background = True  # Set to True to overlay flood on top of your DEM
max_inundation_depth = 4.0  # Ensure this matches your actual max configured depth
water_colormap = 'berlin_r'

#@markdown ### Terrain Visual Settings
terrain_colormap = 'terrain'  #@param ["gray", "gist_earth", "terrain", "copper", "bone"]
dem_filepath = os.path.join(root_folder(), 'dem_file.tif') if 'root_folder' in globals() else '/content/dem_file.tif'

bg_data = None
bg_extent = None
if use_background and os.path.exists(dem_filepath):
    with rasterio.open(dem_filepath) as bg_src:
        bg_data = bg_src.read(1).astype("float32")
        bg_data = np.where(bg_data == bg_src.nodata, np.nan, bg_data)
        b = bg_src.bounds
        bg_extent = [b.left, b.right, b.bottom, b.top]

display_files = []
frames = []

cmap = plt.get_cmap(water_colormap)
color_table = {0: (0, 0, 0, 0)}
for i in range(1, 256):
    rgba = cmap(i / 255.0)
    color_table[i] = tuple(int(x * 255) for x in rgba)

# Force sorting out_files by float value to ensure correct chronological sequence
# This prevents 1.0, 10.0, 2.0 sorting errors if stages were stored as strings
sorted_out_files = sorted(out_files, key=lambda x: float(x[0]))

for stage_raw, extent_path, depth_path in tqdm(sorted_out_files, desc="Generating Progression Frames"):
    # Crucial Fix: Force stage to float so 3.5 doesn't become 3
    stage = float(stage_raw)

    with rasterio.open(depth_path) as src:
        depth = src.read(1).astype("float32")
        profile = src.profile.copy()
        nodata = src.nodata
        b = src.bounds
        depth_extent = [b.left, b.right, b.bottom, b.top]

    valid = np.isfinite(depth)
    if nodata is not None:
        valid &= (depth != nodata)
    valid &= (depth > 0)

    depth_display = np.zeros(depth.shape, dtype=np.uint8)

    if np.any(valid):
        # Scale consistently using max_inundation_depth
        scaled = np.clip(depth[valid] / max_inundation_depth, 0, 1)
        depth_display[valid] = np.maximum(
            1,
            np.round(scaled * 255)
        ).astype(np.uint8)

    display_path = f"/content/depth_display_stage_{stage:.2f}m.tif"
    profile.update(
        driver="GTiff",
        dtype="uint8",
        count=1,
        nodata=0,
        compress="deflate"
    )
    with rasterio.open(display_path, "w", **profile) as dst:
        dst.write(depth_display, 1)
        dst.write_colormap(1, color_table)

    display_files.append((stage, display_path))

    # --- MATPLOTLIB RENDERING ---
    fig, ax = plt.subplots(figsize=(7, 7), dpi=120)
    fig.patch.set_facecolor('#1e1e1e')
    ax.set_facecolor('#1e1e1e')

    if bg_data is not None:
        ax.imshow(bg_data, cmap=terrain_colormap, alpha=0.65, extent=bg_extent)

    masked_arr = np.where(depth_display == 0, np.nan, depth_display)

    im = ax.imshow(
        masked_arr,
        vmin=1,
        vmax=255,
        cmap=water_colormap,
        alpha=0.85,
        extent=depth_extent if bg_extent is None else bg_extent
    )

    # Use .2f to guarantee 1 decimal place (e.g., 3.50 m) shows up in the title
    ax.set_title(
        f"Flood Inundation Stage: {stage:.2f} m",
        color='white',
        fontsize=14,
        pad=10,
        weight='bold'
    )
    ax.axis("off")

    cbar = fig.colorbar(im, ax=ax, shrink=0.65, pad=0.03, orientation='horizontal')
    cbar.set_label('Flood Depth (m)', color='white', fontsize=10)
    cbar.ax.xaxis.set_tick_params(color='white', labelcolor='white')
    cbar.outline.set_edgecolor('white')
    cbar.set_ticks([1, 128, 255])
    cbar.set_ticklabels(['0.1 m', f'{max_inundation_depth/2:.1f} m', f'{max_inundation_depth:.1f} m'])

    plt.tight_layout()

    fig.canvas.draw()
    rgba_buffer, size = fig.canvas.print_to_buffer()
    image = np.frombuffer(rgba_buffer, dtype=np.uint8).reshape(size[1], size[0], 4)

    frames.append(image[:, :, :3])
    plt.close(fig)

gif_path = '/content/flood_progression.gif'
imageio.mimsave(gif_path, frames, fps=2, loop=0)

print(f"\nAnimation saved successfully ({len(frames)} frames): {gif_path}")
DisplayImage(filename=gif_path)

#@title Step 9: Attempt to run GEEMAP Overlay (Reprojected to EPSG:4326 + Google Satellite Hybrid + 0m Option)
import os
import tempfile
import geemap
from ipyleaflet import ImageOverlay, LayersControl
import ipywidgets as widgets
from IPython.display import display
import rasterio
from rasterio.warp import calculate_default_transform, reproject, Resampling
import numpy as np

def reproject_to_epsg4326(input_path, output_path=None):
    """
    Reprojects a GeoTIFF to EPSG:4326 (WGS 84).
    Returns the output filepath and geographic bounds formatted for ipyleaflet.
    """
    if output_path is None:
        temp_dir = tempfile.gettempdir()
        output_path = os.path.join(temp_dir, f"reprojected_{os.path.basename(input_path)}")

    dst_crs = 'EPSG:4326'

    with rasterio.open(input_path) as src:
        transform, width, height = calculate_default_transform(
            src.crs, dst_crs, src.width, src.height, *src.bounds
        )
        kwargs = src.meta.copy()
        kwargs.update({
            'crs': dst_crs,
            'transform': transform,
            'width': width,
            'height': height
        })

        with rasterio.open(output_path, 'w', **kwargs) as dst:
            for i in range(1, src.count + 1):
                reproject(
                    source=rasterio.band(src, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src.transform,
                    src_crs=src.crs,
                    dst_transform=transform,
                    dst_crs=dst_crs,
                    resampling=Resampling.bilinear
                )

    # Re-open reprojected raster to compute exact geographic bounds
    with rasterio.open(output_path) as reprojected_src:
        b = reprojected_src.bounds
        # ipyleaflet bounds: [[south, west], [north, east]]
        bounds_4326 = [[b.bottom, b.left], [b.top, b.right]]

    return output_path, bounds_4326

# 1. Setup Map with Reprojected First Stage
first_stage, first_extent_path, first_depth_path = out_files[0]
first_reprojected_path, first_bounds = reproject_to_epsg4326(first_depth_path)

south, west = first_bounds[0]
north, east = first_bounds[1]
center = [(south + north) / 2, (west + east) / 2]

# Google Satellite Hybrid Tile Layer (lyrs=y enables satellite + road/label overlay)
url = "https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}"
m_flood = geemap.Map(center=center, zoom=16)
m_flood.add_tile_layer(url, name="Google Hybrid", attribution="Google")

# 2. Add Overlays
overlays_dict = {}
for stage, extent_path, depth_path in out_files:
    # Reproject depth raster to EPSG:4326
    reprojected_depth_path, overlay_bounds = reproject_to_epsg4326(depth_path)

    # Pass the reprojected raster path into your data URL helper function
    data_url, _ = depth_tif_to_data_url(reprojected_depth_path, stage, cmap_name="berlin_r")

    # Set default visibility to False (0m option selected by default)
    overlay = ImageOverlay(
        url=data_url,
        bounds=overlay_bounds,
        name=f"Flood depth {stage}m",
        opacity=0.85,
        visible=False
    )
    m_flood.add(overlay)

    # Explicitly use standard python floats as keys
    overlays_dict[round(float(stage), 2)] = overlay

m_flood.add(LayersControl(position="topright"))
m_flood.fit_bounds(first_bounds)

# 3. Create SelectionSlider with 0.0m included as the first option
available_stages = [0.0] + sorted(overlays_dict.keys())

stage_slider = widgets.SelectionSlider(
    options=[(f"{s:.1f}m", s) for s in available_stages],
    value=0.0,  # Set default initial stage to 0.0m (empty map)
    description='Stage (m):',
    continuous_update=False
)

def update_map(change):
    selected_stage = round(float(change.new), 2)
    for s, overlay in overlays_dict.items():
        # Hide all overlays if 0.0m is selected; otherwise enable matching stage
        overlay.visible = (selected_stage != 0.0 and s == selected_stage)

stage_slider.observe(update_map, names='value')

display(m_flood)
display(stage_slider)

import os
import glob
import re
import zipfile
from google.colab import files

fname = 'calumpit' #nospace
zip_filename = f"{fname}_depths.zip"

# 1. STRICT REMOVAL OF PRIOR RENAMED FILES (Matches ONLY '0.50m.tif', '1.25m.tif', etc.)
# Regex pattern explained:
# ^          = start of filename
# \d+\.\d+   = one or more digits, a literal dot, one or more digits
# m\.tif$    = literal 'm.tif' at the very end
strict_renamed_pattern = re.compile(r"^\d+\.\d+m\.tif$")

for f in os.listdir("."):
    if strict_renamed_pattern.match(f) or f == zip_filename:
        try:
            os.remove(f)
            print(f"Removed prior target file: {f}")
        except OSError as e:
            print(f"Error removing {f}: {e}")

# 2. LOCATE ORIGINAL INPUT FILES
depths = glob.glob("hand_depth_stage*tif")
renamed_files = []

# 3. RENAME INPUT FILES TO DEPTH ONLY (e.g., depth_display_stage_0.50m.tif -> 0.50m.tif)
for file_path in depths:
    dir_name, file_name = os.path.split(file_path)
    match = re.search(r"(\d+\.\d+m)", file_name)
    if match:
        new_name = f"{match.group(1)}.tif"
    else:
        new_name = file_name.replace("depth_display_stage_", "")

    new_path = os.path.join(dir_name, new_name)
    os.rename(file_path, new_path)
    renamed_files.append(new_path)

# 4. COMPRESS RENAMED FILES INTO ZIP
with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in renamed_files:
        zipf.write(file_path, arcname=os.path.basename(file_path))

# 5. TRIGGER DOWNLOAD
files.download(zip_filename)